# Copyright (c) 2026 Jani Hautakangas <jani@kodegood.com>
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

enterprise_browser_chrome_browser_enterprise_profile_management_sources = [
  "//enterprise_browser/browser/enterprise/profile_management/enterprise_browser_oidc_auth_navigation_throttle.cc",
  "//enterprise_browser/browser/enterprise/profile_management/enterprise_browser_oidc_auth_navigation_throttle.h",
]

enterprise_browser_chrome_browser_enterprise_signin_sources = [
  "//enterprise_browser/browser/enterprise/signin/enterprise_browser_oidc_auth_signin_interceptor.cc",
  "//enterprise_browser/browser/enterprise/signin/enterprise_browser_oidc_auth_signin_interceptor.h",
  "//enterprise_browser/browser/enterprise/signin/enterprise_browser_oidc_auth_signin_interceptor_factory.cc",
  "//enterprise_browser/browser/enterprise/signin/enterprise_browser_oidc_auth_signin_interceptor_factory.h",
]

enterprise_browser_chrome_browser_policy_sources = [
  "//enterprise_browser/browser/policy/enterprise_browser_policy_provider.cc",
  "//enterprise_browser/browser/policy/enterprise_browser_policy_provider.h",
]

enterprise_browser_chrome_browser_ui_signin_sources = [
  "//enterprise_browser/browser/ui/signin/enterprise_browser_dice_web_signin_interceptor_delegate_helper.cc",
  "//enterprise_browser/browser/ui/signin/enterprise_browser_dice_web_signin_interceptor_delegate_helper.h",
]

enterprise_browser_ebcm_sources = [
  "//enterprise_browser/ebcm/ebcm_auth_util.cc",
  "//enterprise_browser/ebcm/ebcm_auth_util.h",
  "//enterprise_browser/ebcm/ebcm_urls.cc",
  "//enterprise_browser/ebcm/ebcm_urls.h",
]